kind: Pod
apiVersion: v1
metadata:
    labels:
      release: 'stable'
      environment: 'pre-prod'
      relationship: 'child'
      dmzbased: 'false'
      tier: 'front1'
    name: config-resource-pod
    annotations:
      example.com/skipValidation: 'true'
      example.com/MD5Checksum: '23798FGH'
      example.com/BUILDDATE: '3479845'
spec:
    containers:
      - name: test-container
        image: gcr.io/google_containers/busybox:1.24
        command: [ "/bin/sh", "-c", "env" ]
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        env:
          - name: MY_CPU_REQUEST
            valueFrom:
              resourceFieldRef:
                resource: requests.cpu
          - name: MY_CPU_LIMIT
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu
          - name: MY_MEM_REQUEST
            valueFrom:
              resourceFieldRef:
                resource: requests.memory
          - name: MY_MEM_LIMIT
            valueFrom:
              resourceFieldRef:
                resource: limits.memory